spring.application.name=beauminity

## 서버 포트
server.port=8080

## MariaDB 설정 
spring.datasource.url=jdbc:mariadb://localhost:3306/beauminity
spring.datasource.username=root
spring.datasource.password=1111
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

## MyBatis 설정
mybatis.mapper-locations=classpath:/mappers/**/*.xml
mybatis.type-aliases-package=com.miles.beauminity.vo
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# thymeleaf 설정
spring.thymeleaf.cache=false

