spring.application.name=beauminity

## 서버 포트
server.port=8080

## MariaDB 설정 
spring.datasource.url=jdbc:mariadb://192.168.0.26:3306/beauminity
spring.datasource.username=root
spring.datasource.password=0612
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

## MyBatis 설정
mybatis.mapper-locations=classpath:/mappers/**/*.xml
mybatis.type-aliases-package=com.miles.beauminity.vo
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

## thymeleaf 설정
spring.thymeleaf.cache=false

## Gmail STMP 서버 설정
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tns0332@gmail.com
spring.mail.password=znkrgrgwgzmdmmim

## SMTP 인증 및 보안 설정
# SMTP 서버를 통해 메일을 보낼 때 사용자 인증을 거칠 것인지
# 스팸 전송을 막기 위한 것으로 true로 설정할 시
# 위에서 설정한 username과 password를 사용해 구글 서버에 로그인하여 메일을 보냄
spring.mail.properties.mail.smtp.auth=true
# STARTTLS라는 보안 통신 기술 사용 여부로 활성화(enable)하고 필수(required)로 사용하겠다는 의미
# 메일에 아이디, 비밀번호, 본문이 암호화 되지 않으면 해킹의 위험이 있기 때문에
# 처음엔 일반 연결로 시작했다가 보안 암호화 채널(TLS)로 연결을 업그레이드 하도록 만드는 것으로
# STMP(587 포트)를 사용하기 위한 필수 보안 규격
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

## 타임아웃 설정
# 인터넷 연결이 불안정하거나 구글 서버 응답 지연 등 네트워크 지연에 대한 대비로
# 5000은 밀리초로 5초를 의미 타임아웃으로 설정해둔 시간이 지나면 예외를 발생시킴
# 연결 타임아웃 : 스프링 부트 어플리케이션이 구글 서버에 처음 접속 시도 시 얼마나 기다릴지 결정
spring.mail.properties.mail.smtp.connectiontimeout=5000
# 읽기 타임아웃 : 연결 성공 후 구글 서버가 내보내는 응답 메시지를 기다리는 최대 시간
spring.mail.properties.mail.smtp.timeout=5000
# 쓰기 타임아웃 : 스프링 부트 어플리케이션이 구글 서버로 메일 데이터(데이터 스트림)를 전송할 때 기다리는 최대 시간
spring.mail.properties.mail.smtp.writetimeout=5000